name: chicago_taxi_analytics
version: "1.0.0"
config-version: 2

profile: chicago_taxi_analytics

model-paths: ["models"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  chicago_taxi_analytics:
    staging:
      +materialized: incremental
    marts:
      +materialized: table

